spring:
  application:
    name: spring-cloud-service-consumer-ribbon


server:
  port: 8764

eureka:
  instance:
  #    instance-id: testid
  #    appname: test1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/