spring:
  application:
    name: SPRING-CLOUD-SERVICE-PROVIDER

server:
  port: 8762

eureka:
  instance:
#    instance-id: testid
#    appname: test1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 2000
