spring:
  application:
    name: spring-cloud-consumer-feign
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html

server:
  port: 8765

eureka:
  instance:
  #    instance-id: testid
  #    appname: test1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/