spring:
  application:
    name: spring-cloud-consumer-feign

server:
  port: 8765

eureka:
  instance:
  #    instance-id: testid
  #    appname: test1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  metrics:
    polling-interval-ms: 2000
    enabled: true
feign:
  hystrix:
#    enabled: true
  circuitbreaker:
    enabled: true
